
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Max-Age": "86400",
};

interface ContactEmailRequest {
  name: string;
  email: string;
  message: string;
}

// Base64 encoded logo image
const logoBase64 = "iVBORw0KGgoAAAANSUhEUgAABDgAAAQ4CAYAAADsEGyPAAAACXBIWXMAAAsTAAALEwEAmpwYAAAF0WlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNy4yLWMwMDAgNzkuMWI2NWE3OWI0LCAyMDIyLzA2LzEzLTIyOjAxOjAxICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdEV2dD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQjIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgMjQuMCAoTWFjaW50b3NoKSIgeG1wOkNyZWF0ZURhdGU9IjIwMjQtMDMtMDhUMDk6NDI6NDYtMDg6MDAiIHhtcDpNZXRhZGF0YURhdGU9IjIwMjQtMDMtMDhUMDk6NDI6NDYtMDg6MDAiIHhtcDpNb2RpZnlEYXRlPSIyMDI0LTAzLTA4VDA5OjQyOjQ2LTA4OjAwIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjNhOGExNzA0LWNkMTMtNDA0MS1hOWNjLTBkNzI5NmM5ZTFkZiIgeG1wTU06RG9jdW1lbnRJRD0iYWRvYmU6ZG9jaWQ6cGhvdG9zaG9wOjEyOTZmZDA5LTliMGItYzU0Ny05MjVhLTExZjYzOTUyNzk3ZiIgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOjY4NmM1ZDM1LTZkYzAtNDZiYi1iMzVmLTJkZmQ5ZjUzMTkwZiIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjY4NmM1ZDM1LTZkYzAtNDZiYi1iMzVmLTJkZmQ5ZjUzMTkwZiIgc3RFdnQ6d2hlbj0iMjAyNC0wMy0wOFQwOTo0Mjo0Ni0wODowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIDI0LjAgKE1hY2ludG9zaCkiLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjNhOGExNzA0LWNkMTMtNDA0MS1hOWNjLTBkNzI5NmM5ZTFkZiIgc3RFdnQ6d2hlbj0iMjAyNC0wMy0wOFQwOTo0Mjo0Ni0wODowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIDI0LjAgKE1hY2ludG9zaCkiIHN0RXZ0OmNoYW5nZWQ9Ii8iLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3Rvcnk+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+oW+1hwAAIABJREFUeJzs3Xd4VGX+xvH7TCaZ9EYKJKGEXqQj0kFARLD3trqK2FZd17KWtay9K4qKChaKgAjSO6GEElBCSEJ6mfP7YwIBkkkyM+fMzMn9ua7nWkhy5swdY2bmPud53ueYhmEgIiIiIiIiIuLLbFYHEBERERERERE5XSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeSo4RERERERERMTnqeAQEREREREREZ+ngkNEREREREREfJ4KDhERERERERHxeUGeDhARERERERER8XGmaSGI7wAAAABJRU5ErkJggg==";

serve(async (req) => {
  try {
    // Handle CORS preflight requests
    if (req.method === "OPTIONS") {
      return new Response(null, { headers: corsHeaders });
    }

    const resend = new Resend(Deno.env.get("RESEND_API_KEY"));
    const { name, email, message }: ContactEmailRequest = await req.json();

    console.log("Attempting to connect to SMTP server...");

    const { data, error } = await resend.emails.send({
      from: "Amplified Information <contact@amplified.info>",
      to: [email],
      subject: "Thank you for contacting Amplified Information",
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <img src="data:image/png;base64,${logoBase64}" alt="Amplified Information" style="width: 200px; height: auto; margin: 20px 0;" />
          <h1 style="color: #333;">Thank you for reaching out!</h1>
          <p>Dear ${name},</p>
          <p>We have received your message and will get back to you as soon as possible.</p>
          <p>Your message:</p>
          <blockquote style="background-color: #f5f5f5; padding: 15px; border-left: 4px solid #86C232;">
            ${message}
          </blockquote>
          <p>Best regards,<br>The Amplified Information Team</p>
        </div>
      `,
    });

    if (error) {
      console.error("Error sending email:", error);
      return new Response(
        JSON.stringify({ error: error.message }),
        {
          status: 500,
          headers: { "Content-Type": "application/json", ...corsHeaders },
        }
      );
    }

    return new Response(
      JSON.stringify({ message: "Email sent successfully", data }),
      {
        status: 200,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  } catch (error) {
    console.error("Error in send-contact-email function:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
});
