// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwmwxeemfbxgofzisglf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3bXd4ZWVtZmJ4Z29memlzZ2xmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMDM2MDksImV4cCI6MjA1Mzg3OTYwOX0.hmB2ulEKM4GNL6WxBobwdE46GY-JbJdMVdo67r1aVAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);